version: "3.9"

volumes:
  www:

networks:
  proxy:
    external: true
    name: public_proxy

services:
  php:
    image: localhost/p06_php_web2
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - www:/var/www/html
  httpd:
    image: itsziget/httpd24:2.0
    volumes:
      - www:/var/www/html
    environment:
      SRV_PHP: "true"
      SRV_DOCROOT: /var/www/html
      VIRTUAL_HOST: web2.$NIP
    networks:
      - default
      - proxy