name: p10noexpose

networks:
  default:
  client:

x-client-base: &client-base
  depends_on:
    - server
  image: nicolaka/netshoot:v0.13
  command:
    - sleep
    - inf
  init: true

services:

  server:
    build: .
    init: true
    networks:
      - default

  client1:
    <<: *client-base
    networks:
      - default

  client2:
    <<: *client-base
    networks:
      - client
