services:
  test:
    image: bash:5.2
    environment:
      - ALLOCATE
    command:
      - -c
      - 'fallocate -l $ALLOCATE /app/test && echo $(( $(stat /app/test -c "%s") / 1024 / 1024))'
    deploy:
      resources:
        limits:
          memory: 50MB
    mem_swappiness: 0
    tmpfs:
      - /app


